// Translation map for Dhaka transit station/landmark names (Bengali to English)
export const BANGLA_TO_ENGLISH_STATIONS: Record<string, string> = {
  "কালশী": "Kalshi",
  "মিরপুর-১২": "Mirpur-12",
  "মিরপুর-১০": "Mirpur-10",
  "কাজীপাড়া": "Kazipara",
  "শেওড়াপাড়া": "Shewrapara",
  "ফার্মগেট": "Farmgate",
  "শাহবাগ": "Shahbag",
  "পল্টন": "Paltan",
  "গুলিস্তান": "Gulistan",
  "টিকাটুলি": "Tikatuli",
  "সায়দাবাদ": "Sayedabad",
  "যাত্রাবাড়ী": "Jatrabari",
  "যাত্রাবাড়ী": "Jatrabari",
  "সাইনবোর্ড": "Signboard",
  "কাঁচপুরব্রীজ": "Kanchpur Bridge",
  "পল্লবী (মিরপুর-১২)": "Pallabi (Mirpur-12)",
  "মিরপুর-১১১/২": "Mirpur-11.5",
  "বৈকালী হোটেল": "Baikali Hotel",
  "মিরপুর-১১": "Mirpur-11",
  "প্রেসক্লাব": "Press Club",
  "টিএন্ডটি": "T&T",
  "রায়সাহেব বাজার": "Raysahib Bazar",
  "ভিক্টোরিয়া পার্ক": "Victoria Park",
  "দুয়ারীপাড়া": "Duaripara",
  "মিরপুর সাড়ে ১১": "Mirpur 11.5",
  "আগারগাঁও": "Agargaon",
  "ধানমন্ডি": "Dhanmondi",
  "শুক্রাবাদ": "Shukrabad",
  "ঢাকেশ্বরী মন্দির": "Dhakeshwari Temple",
  "দুয়ারিপাড়া": "Duaripara",
  "প্রশিকা": "Proshika",
  "মিরপুর থানা": "Mirpur Thana",
  "মিরপুর-১": "Mirpur-1",
  "আনসারک্যাম্প": "Ansar Camp",
  "আনসার ক্যাম্প": "Ansar Camp",
  "টেকনিক্যাল": "Technical",
  "আসাদগেট": "Asad Gate",
  "সায়েন্সল্যাব": "Science Lab",
  "সাইন্সল্যাব": "Science Lab",
  "বুয়েট": "BUET",
  "পল্লবী (সিরামিক)": "Pallabi (Ceramic)",
  "মিরপুর-১১/২": "Mirpur-11.5",
  "স্টেডিয়াম": "Stadium",
  "নটরড্যাম কলেজ": "Notre Dame College",
  "চিড়িয়াখানা": "Zoo",
  "দারুসালাম": "Darussalam",
  "দারুসসালাম": "Darussalam",
  "কল্যাণপুর": "Kalyanpur",
  "শ্যامলী": "Shyamoli",
  "কলেজগেট": "College Gate",
  "কলেজগেইট": "College Gate",
  "কাওরানবাজার": "Karwan Bazar",
  "ইত্তেফাক": "Ittefaq",
  "সায়েদাবাদ": "Sayedabad",
  "কলাবাগান": "Kalabagan",
  "কাটাবন": "Katabon",
  "গুলিস্তান মোড়": "Gulistan Intersection",
  "বাংলাদেশ ব্যাংক": "Bangladesh Bank",
  "ইসিবি মোড়": "ECB More",
  "ইসিবি চত্বর": "ECB Chattar",
  "শিশুমেলা": "Shishu Mela",
  "মানিকমিয়া এভিনিউ": "Manik Mia Avenue",
  "আজিমপুর": "Azimpur",
  "মিরপুর মাজার রোড": "Mirpur Mazar Road",
  "রাসেল স্কয়ার": "Russell Square",
  "নিউমার্কেট": "New Market",
  "নিউ মার্কেট": "New Market",
  "নীлক্ষেত": "Nilkhet",
  "মিরপুর (১৪)": "Mirpur-14",
  "মিরপুর-১৪": "Mirpur-14",
  "মিরপুর (১০)": "Mirpur-10",
  "মিরপুর (১)": "Mirpur-1",
  "বাংলা কলেজ": "Bangla College",
  "শাপলা চত্বর": "Shapla Chattar",
  "কমলাপুর": "Kamalapur",
  "কমলাপুর ষ্টেশন": "Kamalapur Station",
  "কমলাপুর স্টেশন": "Kamalapur Station",
  "বাসাবো": "Basabo",
  "খিলগাও রেলগেট": "Khilgaon Railgate",
  "খিলগাও তালতলা": "Khilgaon Taltola",
  "ভিক্টোরিয়াপার্ক": "Victoria Park",
  "বাইপাইল": "Baipail",
  "কামারপাড়া": "Kamarpara",
  "আজমপুর": "Azampur",
  "বিশ্বরোড": "Biswaroad",
  "কুড়িল বিশ্বরোড": "Kuril Biswaroad",
  "স্টাফরোড": "Staff Road",
  "কakli": "Kakoli",
  "কাকলি": "Kakoli",
  "মহাখালী": "Mohakhali",
  "ফুলবাড়িয়া": "Fulbaria",
  "ফুলবাড়ীয়া": "Fulbaria",
  "বাবু বাজার ব্রীজ": "Babu Bazar Bridge",
  "কেরানীগঞ্জ": "Keraniganj",
  "ইউবিএল": "UBL",
  "বালুঘাট": "Balughat",
  "উত্তরা (রাণীগঞ্জ)": "Uttara (Raniganj)",
  "উত্তরা (রানীগঞ্জ)": "Uttara (Raniganj)",
  "নতুন বাজার": "Notun Bazar",
  "রামপুরা টিভি সেন্টার": "Rampura TV Center",
  "টিভি সেন্টার": "TV Center",
  "মালিবাগ": "Malibagh",
  "কাকরাইল": "Kakrail",
  "বঙ্গবন্ধু এভিনিউ": "Bangabandhu Avenue",
  "বনশ্রী": "Banasree",
  "রামপুরা": "Rampura",
  "শ্যامলী রিং রোড": "Shyamoli Ring Road",
  "মোহাম্মদপুর শিয়া মসজিদ": "Mohammadpur Shia Mosque",
  "পীরজঙ্গী মাজার": "Peerjongi Mazar",
  "মগবাজার": "Moghbazar",
  "বাংলা মটর": "Bangla Motor",
  "বাংলামটর": "Bangla Motor",
  "গুলশান-১": "Gulshan-1",
  "গুলশান-২": "Gulshan-2",
  "সাতরাস্তা": "Satrasta",
  "নাবিস্কো": "Nabisco",
  "তিতুমীর কলেজ": "Titumir College",
  "মৌচাক": "Mouchak",
  "জিগাতলা": "Jigatola",
  "মোহাম্মদপুর (আসাদ এভিনিউ)": "Mohammadpur (Asad Avenue)",
  "মোঃপুর (জাপান গার্ডেন সিটি)": "Mohammadpur (Japan Garden)",
  "ফকিরাপুল": "Fakirapool",
  "দয়াগঞ্জ রোড": "Doyaganj Road",
  "পোস্তগোলা": "Postogola",
  "ঘাটারচর": "Ghatarchara",
  "মোঃপুর": "Mohammadpur",
  "শঙ্কর": "Shankar",
  "ধানমন্ডি-১৫": "Dhanmondi-15",
  "ঢাকা সিটি কলেজ": "Dhaka City College",
  "ঢাকা কলেজ": "Dhaka College",
  "ধোপখোলা": "Dhopkhola",
  "মোহাম্মদপুর": "Mohammadpur",
  "টাউন হল": "Town Hall",
  "मध्य बाड्डा": "Madhya Badda",
  "উত্তর বাড্ডা": "North Badda",
  "বসুন্ধরা": "Basundhara",
  "নৰ্দ্দা": "Norda",
  "নিউ এয়ারপোর্ট": "New Airport",
  "রাজলক্ষ্মী": "Rajlakshmi",
  "হাউজ বিল্ডিং": "House Building",
  "রাজমনি": "Rajmoni",
  "আবুল হোটেল": "Abul Hotel",
  "সাভার": "Savar",
  "হেমায়েতপুর": "Hemayetpur",
  "গাবতলী": "Gabtoli",
  "গাবতলি": "Gabtoli",
  "নুতন বাজার": "Notun Bazar",
  "প্রিয়াঙ্গন গেট": "Priyangon Gate",
  "ইস্টার্ন হাউজিং": "Eastern Housing",
  "ধওর": "Dhaur",
  "ধওর ব্রীজ": "Dhaur Bridge",
  "জিরাব": "Zirabo",
  "ফ্যান্টাসী": "Fantasy Kingdom",
  "ইপিজেড": "EPZ",
  "জিরানী": "Zirani",
  "নন্দনপার্ক": "Nandan Park",
  "চন্দ্রা": "Chandra",
  "লিংক রোড": "Link Road",
  "নাঃগঞ্জ লিংক রোড": "Narayanganj Link Road",
  "আমুলিয়া স্টাফ কোয়ার্টার": "Amulia Staff Quarter"
};

/**
 * Gets the English translation of a Bengali station name.
 * If the station name is not found in the map, it attempts to return a clean version
 * or the name itself.
 */
export function getEnglishName(banglaName: string): string {
  if (!banglaName) return "";
  const trimmed = banglaName.trim();
  if (BANGLA_TO_ENGLISH_STATIONS[trimmed]) {
    return BANGLA_TO_ENGLISH_STATIONS[trimmed];
  }
  
  // Try matching stripped variants to make translation extremely reliable
  const normalizedKey = trimmed.replace(/\s+/g, "").replace(/[\-\(\)\,\.\/]/g, "");
  for (const [k, v] of Object.entries(BANGLA_TO_ENGLISH_STATIONS)) {
    const normK = k.replace(/\s+/g, "").replace(/[\-\(\)\,\.\/]/g, "");
    if (normK === normalizedKey) {
      return v;
    }
  }

  return trimmed; // fallback to original name
}
